--- 
pool: 
  vmImage: ubuntu-latest
steps: 
  - 
    inputs: 
      goals: package
      javaHomeOption: JDKVersion
      jdkArchitectureOption: x64
      jdkVersionOption: "1.8"
      mavenOptions: "-Xmx3072m"
      mavenPomFile: pom.xml
      publishJUnitResults: true
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
    task: Maven@3
trigger: 
  - main
